apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-healthapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-healthapp
  template:
    metadata:
      labels:
        app: test-healthapp
    spec:
      containers:
        - name: test-healthapp
          image: kumarch99/test-healthapp:v1
          ports:
            - containerPort: 8999